[package]
name = "shicsk"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = { version = "0.7.5", features = ["editor"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
